export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const TOGGLE_EDITMODE = 'APP/TOGGLE_EDITMODE';
export const OPEN_DRAWER = 'APP/OPEN_DRAWER';

export const SET_SONGDATA = 'SONGS/SET_ROWS';
export const ADD_SONG = 'SONGS/ADD_ROWS';
export const REMOVE_SONG = 'SONGS/REMOVE_SONG';
export const EDIT_SONG = 'SONGS/EDIT_SONG';
export const TOGGLE_ACTIVE = 'SONGS/TOGGLE_ACTIVE';
export const SET_SEARCHTEXT = 'SONGS/SET_SEARCHTEXT';
export const SET_FILTER_SONG = 'SONGS/SET_FILTER_SONG';
export const SET_SELECTED_SONG = 'SONGS/SET_SELECTED';
export const EDIT_SONGS_TIMESPLAYED = 'SONGS/EDIT_TIMESPLAYED';

export const SET_QUEUEDATA = 'QUEUE/SET_ROWS';
export const CHANGE_POSITION = 'QUEUE/CHANGE_POSITION';
export const ADD_SONG_IN_QUEUE = 'QUEUE/ADD_SONG_IN_QUEUE';
export const REMOVE_SONG_IN_QUEUE = 'QUEUE/REMOVE_SONG_IN_QUEUE';
export const UPDATE_SONG_QUEUE = 'QUEUE/UPDATE_SONG_QUEUE';
export const UPDATE_SONG_HISTORY = 'QUEUE/UPDATE_SONG_HISTORY';
export const SET_SELECTED_QUEUE = 'QUEUE/SET_SELECTED';

export const SET_SAVEDQUEUEDATA = 'SAVED-QUEUE/SET_ROWS';
export const ADD_SONG_IN_SAVEDQUEUE = 'SAVED-QUEUE/ADD_SONG_IN_QUEUE';
export const REMOVE_SONG_SAVEDQUEUE = 'SAVED-QUEUE/REMOVE_SONG';
export const SET_SELECTED_SAVEDQUEUE = 'SAVED-QUEUE/SET_SELECTED';
export const SET_SEARCHTEXT_SAVEDQUEUE = 'SAVED-QUEUE/SET_SEARCHTEXT';

export const SET_HISTORYDATA = 'HISTORY/SET_ROWS';
export const ADD_SONG_IN_HISTORY = 'HISTORY/ADD_SONG_IN_HISTORY';
export const EDIT_SONG_HISTORY = 'HISTORY/EDIT_SONG_HISTORY';
export const REMOVE_SONG_HISTORY = 'HISTORY/REMOVE_SONG';
export const SET_SELECTED_HISTORY = 'HISTORY/SET_SELECTED';
export const SET_SEARCHTEXT_HISTORY = 'HISTORY/SET_SEARCHTEXT';
export const SET_FILTER_HISTORY = 'HISTORY/SET_SEARCHTEXT';

export const SET_ATTRIBUTESDATA = 'ATTRIBUTES/SET_ROWS';
export const ADD_ATTRIBUTES = 'ATTRIBUTES/ADD_ROWS';
export const REMOVE_ATTRIBUTES  = 'ATTRIBUTES/REMOVE_SONG';
export const EDIT_ATTRIBUTES  = 'ATTRIBUTES/EDIT_SONG';
export const SET_SELECTED_ATTRIBUTES  = 'ATTRIBUTES/SET_SELECTED';